config/routes.rb
Rails.application.routes.draw do

  resources :top, only: :index
  resources :books, only: [:create]
  post 'books/registration' => 'books#registration'
  get 'books/search' => 'books#search'
  root 'top#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/book_test.rb
class BookTest

  # プロパティの設定
  attr_accessor :title, :image_url, :url

  def initialize(title, image_url, url)
    @title = title
    @image_url = image_url
    @url = url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def search
    if params[:keyword].present?
      # デバックログ出力するために記述
      Amazon::Ecs.debug = true

      # Amazon::Ecs::Responceオブジェクトの取得
      books = Amazon::Ecs.item_search(
        params[:keyword],
        search_index:  'Books',
        dataType: 'script',
        response_group: 'ItemAttributes, Images',
        country:  'jp',
        power: "Not kindle"
        )

      # 本のタイトル,画像URL, 詳細ページURLの取得
      @books = []
      books.items.each do |item|
        book = Book.new(
          title: item.get('ItemAttributes/Title'),
          image_url: item.get('LargeImage/URL'),
          url: item.get('DetailPageURL'),
          )
        @books << book
      end
    end
  end

  def registration
    @book = Book.new(registration_params)
  end

  def create
    @book = Book.create(create_params)
  end

  private
  def registration_params
    params.require(:book).permit(:title, :image_url, :url)
  end

  def create_params
    params.require(:book).permit(:title, :image_url, :url)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @books = Book.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/books/_book_list.html.erb
<% if @books.present? %>
  <% @books.each do |book| %>
    <div class="col-xs-6 col-lg-4">
      <%= link_to (image_tag(book.image_url, style: "width: 70px;height: 100px;display: inline-block;")), book.url %>
      <%= book.title %>
      <%= form_for book, url: books_registration_path do |f| %>
        <%= f.hidden_field :title %>
        <%= f.hidden_field :image_url %>
        <%= f.hidden_field :url %>
        <%= f.submit '登録' %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/books/create.html.erb
<p>本の登録が完了しました！</p>
<%= link_to(image_tag(@book.image_url, style: "width:70px;height: 100px;"), @book.url) %>
<%= @book.title %>

app/views/books/registration.html.erb
<%= link_to (image_tag(@book.image_url, style: "width: 70px;height: 100px;display: inline-block;")), @book.url %>
<%= @book.title %>
<%= form_for @book, url: books_path do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :image_url %>
  <%= f.hidden_field :url %>
  <%= f.submit 'この本を登録する！' %>
<% end %>

app/views/books/search.html.erb
<div class='container'>
  <div id="search-box">
    <%= form_tag('/books/search', method: :get) do %>
    <%= text_field_tag :book, "",  id: "book_search", name: "keyword", placeholder: "キーワードを打ち込んでください", style: "width: 200px;"%><button title="検索" type="submit">検索</button>
    <% end %>
  </div>
  <% if @books.present? %>
  <h2>検索結果</h2>
  <div class="row">
    <!-- 取得した書籍を表示 -->
    <%= render partial: 'book_list' %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OriappProto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Freelancer - Start Bootstrap Theme</title>

  <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/freelancer.css" rel="stylesheet">

  <!-- Original CSS -->
  <link href="my.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
  <script src="js/classie.js"></script>
  <script src="js/cbpAnimatedHeader.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="js/jqBootstrapValidation.js"></script>
  <script src="js/contact_me.js"></script>

  <!-- Custom Theme JavaScript -->
  <script src="js/freelancer.js"></script>

</head>
<body id="page-top" class="index">

  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#page-top">Book Share</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="hidden">
            <a href="#page-top"></a>
          </li>
          <li class="page-scroll">
            <a href="#portfolio">Portfolio</a>
          </li>
          <li class="page-scroll">
            <a href="#about">About</a>
          </li>
          <li class="page-scroll">
            <a href="#contact">Contact</a>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>

  <div style="margin-top: 130px">
    <%= yield %>
  </div>

</body>
</html>

app/views/top/_book_list.html.erb
<% if @books.present? %>
  <% @books.each do |book| %>
    <div class="col-xs-6 col-lg-4">
      <%= link_to (image_tag(book.image_url, style: "width: 70px;height: 100px;display: inline-block;")), book.url %>
      <%= book.title %>
      <%= form_for book, url: books_registration_path do |f| %>
        <%= f.hidden_field :title %>
        <%= f.hidden_field :image_url %>
        <%= f.hidden_field :url %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/top/index.html.erb
<div class='container'>
  <% if @books.present? %>
  <h2>書籍一覧</h2>
  <div class="row">
    <!-- 取得した書籍を表示 -->
    <%= render partial: 'book_list' %>
  </div>
  <% end %>
</div>